# Eksik Veriler

In [187]:
import pandas as pd
import numpy as np
import seaborn as sns

In [188]:
df = pd.read_csv("veriler.csv")

In [189]:
df

   ulke  boy  kilo  yas cinsiyet
0    tr  130    30   10        e
1    tr  125    36   11        e
2    tr  135    34   10        k
3    tr  133    30    9        k
4    tr  129    38   12        e
5    tr  180    90   30        e
6    tr  190    80   25        e
7    tr  175    90   35        e
8    tr  177    60   22        k
9    us  185   105   33        e
10   us  165    55   27        k
11   us  155    50   44        k
12   us  160    58   39        k
13   us  162    59   41        k
14   us  167    62   55        k
15   fr  174    70   47        e
16   fr  193    90   23        e
17   fr  187    80   27        e
18   fr  183    88   28        e
19   fr  159    40   29        k
20   fr  164    66   32        k
21   fr  166    56   42        k

In [190]:
c = df.iloc[:,-1:].values
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
c[:,-1] = le.fit_transform(df.iloc[:,-1])
ohe = preprocessing.OneHotEncoder()
c = ohe.fit_transform(c).toarray()

In [191]:
sonuc3 = pd.DataFrame(data=c[:,:1],index=range(22),columns=["cinsiyeti"])

In [192]:
df = pd.concat([df,sonuc3],axis=1)

In [193]:
df.drop(["cinsiyet"],axis=1,inplace=True)

In [194]:
df

   ulke  boy  kilo  yas  cinsiyeti
0    tr  130    30   10        1.0
1    tr  125    36   11        1.0
2    tr  135    34   10        0.0
3    tr  133    30    9        0.0
4    tr  129    38   12        1.0
5    tr  180    90   30        1.0
6    tr  190    80   25        1.0
7    tr  175    90   35        1.0
8    tr  177    60   22        0.0
9    us  185   105   33        1.0
10   us  165    55   27        0.0
11   us  155    50   44        0.0
12   us  160    58   39        0.0
13   us  162    59   41        0.0
14   us  167    62   55        0.0
15   fr  174    70   47        1.0
16   fr  193    90   23        1.0
17   fr  187    80   27        1.0
18   fr  183    88   28        1.0
19   fr  159    40   29        0.0
20   fr  164    66   32        0.0
21   fr  166    56   42        0.0

In [195]:
from sklearn.model_selection import train_test_split

In [196]:
df= pd.concat([df,pd.get_dummies(df["ulke"])],axis=1)
df.drop(["ulke"],axis=1,inplace=True)
X = df.drop(["boy"],axis=1)
Y = df["boy"]

In [197]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.33,random_state=0)
x_test

    kilo  yas  cinsiyeti  fr  tr  us
20    66   32        0.0   1   0   0
10    55   27        0.0   0   0   1
14    62   55        0.0   0   0   1
13    59   41        0.0   0   0   1
1     36   11        1.0   0   1   0
21    56   42        0.0   1   0   0
11    50   44        0.0   0   0   1
19    40   29        0.0   1   0   0

In [198]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [199]:
y_predict = regressor.predict(x_test)

In [200]:
regressor.score(x_test,y_test)

0.5269561623575618

In [201]:
y_test.array

<PandasArray>
[164, 165, 167, 162, 125, 166, 155, 159]
Length: 8, dtype: int64

In [202]:
y_predict

array([182.26638686, 152.87161474, 162.79386375, 158.30668577,
       130.82888952, 173.96138408, 150.12782663, 157.26898922])

# Backward Elimination- Geriye Doğru Eleme

In [206]:
import statsmodels.api as sm
dene= np.append(arr=np.ones((22,1)).astype(int),values=X,axis=1)

In [207]:
dene

array([[  1.,  30.,  10.,   1.,   0.,   1.,   0.],
       [  1.,  36.,  11.,   1.,   0.,   1.,   0.],
       [  1.,  34.,  10.,   0.,   0.,   1.,   0.],
       [  1.,  30.,   9.,   0.,   0.,   1.,   0.],
       [  1.,  38.,  12.,   1.,   0.,   1.,   0.],
       [  1.,  90.,  30.,   1.,   0.,   1.,   0.],
       [  1.,  80.,  25.,   1.,   0.,   1.,   0.],
       [  1.,  90.,  35.,   1.,   0.,   1.,   0.],
       [  1.,  60.,  22.,   0.,   0.,   1.,   0.],
       [  1., 105.,  33.,   1.,   0.,   0.,   1.],
       [  1.,  55.,  27.,   0.,   0.,   0.,   1.],
       [  1.,  50.,  44.,   0.,   0.,   0.,   1.],
       [  1.,  58.,  39.,   0.,   0.,   0.,   1.],
       [  1.,  59.,  41.,   0.,   0.,   0.,   1.],
       [  1.,  62.,  55.,   0.,   0.,   0.,   1.],
       [  1.,  70.,  47.,   1.,   1.,   0.,   0.],
       [  1.,  90.,  23.,   1.,   1.,   0.,   0.],
       [  1.,  80.,  27.,   1.,   1.,   0.,   0.],
       [  1.,  88.,  28.,   1.,   1.,   0.,   0.],
       [  1.,  40.,  29.,   0.,   1.,   0.,   0.],
       [  1.,  66.,  32.,   0.,   1.,   0.,   0.],
       [  1.,  56.,  42.,   0.,   1.,   0.,   0.]])