In [27]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression

In [28]:
veriler = pd.read_csv("odev_tenis.csv")

In [29]:
veriler = pd.concat([veriler,pd.get_dummies(veriler["outlook"])],axis=1)
veriler.drop(["outlook"],axis=1,inplace=True)

In [30]:
veriler

    temperature  humidity  windy play  overcast  rainy  sunny
0            85        85  False   no         0      0      1
1            80        90   True   no         0      0      1
2            83        86  False  yes         1      0      0
3            70        96  False  yes         0      1      0
4            68        80  False  yes         0      1      0
5            65        70   True   no         0      1      0
6            64        65   True  yes         1      0      0
7            72        95  False   no         0      0      1
8            69        70  False  yes         0      0      1
9            75        80  False  yes         0      1      0
10           75        70   True  yes         0      0      1
11           72        90   True  yes         1      0      0
12           81        75  False  yes         1      0      0
13           71        91   True   no         0      1      0

In [39]:
windy = []
for i in veriler["windy"].values:
    windy.append(int(i))

In [40]:
windy

[0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1]

In [43]:
veriler["windy_cat"] = windy

In [45]:
veriler.drop(["windy"],axis=1,inplace=True)

In [46]:
veriler

    temperature  humidity play  overcast  rainy  sunny  windy_cat
0            85        85   no         0      0      1          0
1            80        90   no         0      0      1          1
2            83        86  yes         1      0      0          0
3            70        96  yes         0      1      0          0
4            68        80  yes         0      1      0          0
5            65        70   no         0      1      0          1
6            64        65  yes         1      0      0          1
7            72        95   no         0      0      1          0
8            69        70  yes         0      0      1          0
9            75        80  yes         0      1      0          0
10           75        70  yes         0      0      1          1
11           72        90  yes         1      0      0          1
12           81        75  yes         1      0      0          0
13           71        91   no         0      1      0          1

In [48]:
veriler["play"].replace(["yes","no"],[1,0],inplace=True)

In [49]:
veriler

    temperature  humidity  play  overcast  rainy  sunny  windy_cat
0            85        85     0         0      0      1          0
1            80        90     0         0      0      1          1
2            83        86     1         1      0      0          0
3            70        96     1         0      1      0          0
4            68        80     1         0      1      0          0
5            65        70     0         0      1      0          1
6            64        65     1         1      0      0          1
7            72        95     0         0      0      1          0
8            69        70     1         0      0      1          0
9            75        80     1         0      1      0          0
10           75        70     1         0      0      1          1
11           72        90     1         1      0      0          1
12           81        75     1         1      0      0          0
13           71        91     0         0      1      0          1

In [51]:
X = veriler.drop(["temperature"],axis=1)
Y= veriler["temperature"]

In [52]:
from sklearn.model_selection import train_test_split

In [54]:
x_train,x_test,y_train,y_test =train_test_split(X,Y,random_state=0,test_size=0.33)

In [55]:
linearModel = LinearRegression()

In [56]:
linearModel.fit(x_train,y_train)

LinearRegression()

In [57]:
linearModel.score(x_test,y_test)

-0.781766901973636

In [58]:
linearModel.predict(x_test)

array([79.29254445, 78.27431645, 71.60197221, 78.49469595, 81.09696698])

In [59]:
y_test

8     69
6     64
4     68
11    72
2     83
Name: temperature, dtype: int64

In [60]:
veriler

    temperature  humidity  play  overcast  rainy  sunny  windy_cat
0            85        85     0         0      0      1          0
1            80        90     0         0      0      1          1
2            83        86     1         1      0      0          0
3            70        96     1         0      1      0          0
4            68        80     1         0      1      0          0
5            65        70     0         0      1      0          1
6            64        65     1         1      0      0          1
7            72        95     0         0      0      1          0
8            69        70     1         0      0      1          0
9            75        80     1         0      1      0          0
10           75        70     1         0      0      1          1
11           72        90     1         1      0      0          1
12           81        75     1         1      0      0          0
13           71        91     0         0      1      0          1