In [57]:
from sklearn.metrics import r2_score
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [58]:
def r2scoreolc(df,hedef,ekstra_dusur=[]):

    """
    GİRİLEN DF DEĞERİNDE KESİNLİKE KATEGORİK DEĞERLER BULUNMAMALIDIR.
    YA DÜŞÜRÜLMELİ YA DA SAYISAL DEĞERE DEĞİŞTİRİLMELİDİR: 
    BU GELİŞTİRİCİNİN SORUMLULUĞUNDADIR. 
    
    """
    X= df.drop([hedef]+ekstra_dusur,axis=1)
    Y=df[hedef].values
    Y=pd.DataFrame(Y,columns=[hedef])

    linear_model = LinearRegression()
    linear_model.fit(X,Y)
    print("-------Linear Model-----")
    print(r2_score(Y,linear_model.predict(X)))

    poly_reg = PolynomialFeatures(degree=10)
    x_poly = poly_reg.fit_transform(X)
    lin_reg2 = LinearRegression()
    lin_reg2.fit(x_poly,Y)
    print("-------Polinom Model-----")
    print(r2_score(Y,lin_reg2.predict(x_poly)))


    sc1 = StandardScaler()
    X_olcekli = sc1.fit_transform(X)

    sc2 = StandardScaler()
    Y_olcekli = sc2.fit_transform(Y)
    svr_model = SVR()
    svr_model.fit(X_olcekli,Y_olcekli)
    print("-------SVR-----")
    print(r2_score(Y_olcekli,svr_model.predict(X_olcekli)))

    decision_model = DecisionTreeRegressor()
    decision_model.fit(X,Y)
    print("-------DECİSİON TREE-----")
    print(r2_score(Y,decision_model.predict(X)))

    random_model =RandomForestRegressor()
    random_model.fit(X,Y)
    print("-------Random Decision-----")
    print(r2_score(Y,random_model.predict(X)))

In [59]:
df = pd.read_csv("maaslar_yeni.csv")
df

    Calisan ID             unvan  UnvanSeviyesi  Kidem  Puan   maas
0            1             Cayci              1      5    70   2250
1            2          Sekreter              2      5    70   2500
2            3  Uzman Yardimcisi              3      5    70   3000
3            4             Uzman              4      5    70   4000
4            5  Proje Yoneticisi              5      5    70   5500
5            6               Sef              6      5    70   7500
6            7             Mudur              7      5    70  10000
7            8          Direktor              8      5    70  15000
8            9           C-level              9      5    70  25000
9           10               CEO             10      5    70  50000
10          11             Cayci              1      7    99   2000
11          12          Sekreter              2      7     9   2500
12          13  Uzman Yardimcisi              3      7    62   4000
13          14             Uzman              4      4    38   3000
14          15  Proje Yoneticisi              5      1    80   5000
15          16               Sef              6      2    35   5000
16          17             Mudur              7      8    99  12000
17          18          Direktor              8      4    58  11000
18          19           C-level              9      2    20  15000
19          20               CEO             10      4    42  22000
20          21             Cayci              1      8    11   2200
21          22          Sekreter              2      2    53   2200
22          23  Uzman Yardimcisi              3      8    50   2800
23          24             Uzman              4      9    91   6000
24          25  Proje Yoneticisi              5      9    71   5400
25          26               Sef              6      1     2   4000
26          27             Mudur              7     10    81  12000
27          28          Direktor              8     10    38  10000
28          29           C-level              9      1    50  15000
29          30               CEO             10      9    83  60000

In [60]:
df.drop(["unvan","Calisan ID"],axis=1,inplace=True)
X = df.drop(["maas"],axis=1)
Y= df.loc[:,"maas"]

In [61]:
Y=pd.DataFrame(Y,columns=["maas"])
Y

     maas
0    2250
1    2500
2    3000
3    4000
4    5500
5    7500
6   10000
7   15000
8   25000
9   50000
10   2000
11   2500
12   4000
13   3000
14   5000
15   5000
16  12000
17  11000
18  15000
19  22000
20   2200
21   2200
22   2800
23   6000
24   5400
25   4000
26  12000
27  10000
28  15000
29  60000

In [62]:
r2scoreolc(df,"maas")

-------Linear Model-----
0.5857207050854021
-------Polinom Model-----
0.9999999937510429
-------SVR-----
0.6287203839391853
-------DECİSİON TREE-----
1.0
-------Random Decision-----
0.9610336714786537

c:\Users\Özdemir\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Özdemir\AppData\Local\Temp\ipykernel_10512\4033414134.py:42: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  random_model.fit(X,Y)

In [63]:
X = X.values

In [64]:
linear_model = LinearRegression()
linear_model.fit(X,Y)

LinearRegression()

In [68]:
print(linear_model.predict([[10,10,100]]))
print(linear_model.predict([[7,10,100]]))

[[32861.59416921]]
[[22565.31899734]]

In [75]:
print(svr_model.predict([[10,10,100]]))
print(svr_model.predict([[7,10,100]]))

[5450.56073841]
[5450.49196898]